# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Report Custom Warning
      run: |
        echo "::warning file=temp.swift,line=13,col=19::Warning: Leak detected in 'a'."
        echo "::warning file=temp.swift,line=20,col=27::Warning: Leak detected in 'aa'."

