# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Report Custom Warning
      run: |
        echo "${{toJson(github)}}""

        curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://github.com/yume190/LeakDetect/releases/download/0.0.4.2/leakDetect" \
          -o leakDetect

        chmod +x leakDetect

        sha=${{github.sha}} repository=${{github.repository}} auth=${{ secrets.GITHUB_TOKEN }} issue=${{ github.event.number }} ./leakDetect \
              --sdk macosx \
              --reporter custom \
              --file Sources/ActionTest/ActionTest.swift
        # ./entrypoint.sh ${{github.sha}} ${{github.repository}} ${{ secrets.GITHUB_TOKEN }} ${{ github.event.number }}
